---
name: Checks

on: [push, pull_request]

jobs:
    lint-test:
        name: Lint and Test
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Checkout
              uses: actions/checkout@v3
            - name: Run Tests
              run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
            - name: Run Linting
              run: docker-compose run --rm app sh -c "flake8"
